There was an error using rcon trying again.....
> Connection failed.
Error 111: Connection refused <
Connection failed.
Error 111: Connection refused
./factorio-task.sh: line 696: runSQLOutput: command not found
The server is currently reseting or the data in the database is wrong please be patient or correct it
Starting again in 5 seconds
./factorio-task.sh: line 659: runSQLOutput: command not found
The server is currently reseting or the data in the database is wrong please be patient or correct it
Finished
